# Generated by Django 3.2.7 on 2021-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
